### ISSUE TITLE
Why not just `target_link_libraries(my_target Eigen3::Eigen)`?

### ISSUE THREAD

**Issue by VRichardJP** [ros2/eigen3_cmake_module#7]
I understand Eigen3 does create standard cmake variables, and thus does not work well with `ament_target_dependencies`. But is there anything wrong with `target_link_libraries(my_target Eigen3::Eigen)`?

According to [the documentation](https://docs.ros.org/en/foxy/How-To-Guides/Ament-CMake-Documentation.html), we can write this for `ament_auto` based packages:
- `package.xml`
```xml
<depend>eigen</depend>
```
- `CMakeLists.txt`
```cmake
find_package(Eigen3 REQUIRED)
ament_auto_add_library(my_target 
  # ...
)
target_link_libraries(my_target Eigen3::Eigen)
```

VS using `eigen3_cmake_module`:
- `package.xml`
```xml
<depend>eigen3_cmake_module</depend>
<depend>eigen</depend>
```
```cmake
find_package(Eigen3 REQUIRED)
ament_auto_add_library(my_target 
  # ...
)
ament_target_dependencies(my_target Eigen3)
```

Is there any difference between the two? Or is there a chance that with `eigen3_cmake_module`, it would be possible to skip the `find_package` and `ament_target_dependencies` thanks to `ament_auto` macros?

**Comment by clalancette** [comment]
In short, this package exists due to some broken Eigen CMake logic for old versions of Eigen.  In newer versions of Eigen, this has been corrected.

Unfortunately, we are still using an old, broken version of Eigen3 for Windows, so we still need this for now.  Once that is fixed, we can actually drop this package completely and just rely on the `Eigen3::Eigen` target like you mention above.

**Comment by VRichardJP** [comment]
So this problem does not concern Linux distributions? or only very old? (e.g. Ubuntu 16.04)

**Comment by clalancette** [comment]
> So this problem does not concern Linux distributions? or only very old? (e.g. Ubuntu 16.04)

As far as I understand, yes.  That said, we haven't tested that theory out yet.
